name: Daily Worker Rotation

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  rotate-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate random worker name
        id: random
        run: |
          # Generate a random 8-character name
          NEW_NAME=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 8 | head -n 1)
          echo "name=$NEW_NAME" >> $GITHUB_OUTPUT
          echo "Generated worker name: $NEW_NAME"

      - name: Update wrangler.toml with new name
        run: |
          sed -i "s/name = \".*\"/name = \"${{ steps.random.outputs.name }}-proxy\"/" wrangler.toml
          echo "Updated wrangler.toml:"
          cat wrangler.toml

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Cloudflare
        run: |
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | npx wrangler auth login --api-token
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy new worker
        run: npx wrangler deploy --compatibility-date 2024-01-01

      - name: Get deployed worker URL
        id: worker-url
        run: |
          if [ -n "${{ secrets.CUSTOM_DOMAIN }}" ]; then
            WORKER_URL="https://${{ steps.random.outputs.name }}.${{ secrets.CUSTOM_DOMAIN }}"
          else
            WORKER_URL="https://${{ steps.random.outputs.name }}-proxy.abesternheim.workers.dev"
          fi
          echo "url=$WORKER_URL" >> $GITHUB_OUTPUT
          echo "Worker deployed at: $WORKER_URL"

      - name: Update daily URL file
        run: |
          echo "# Current Daily Worker URL" > CURRENT_URL.md
          echo "Today's worker URL: ${{ steps.worker-url.outputs.url }}" >> CURRENT_URL.md
          echo "Deployed at: $(date -u)" >> CURRENT_URL.md
          echo "" >> CURRENT_URL.md
          echo "This URL will be updated daily at midnight UTC." >> CURRENT_URL.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add wrangler.toml CURRENT_URL.md
          git diff --staged --quiet || git commit -m "🔄 Daily worker rotation: ${{ steps.random.outputs.name }}-proxy"
          git push

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "daily-${{ steps.random.outputs.name }}"
          release_name: "Daily Worker: ${{ steps.random.outputs.name }}-proxy"
          body: |
            🔄 **Daily Worker Rotation**

            **New URL:** ${{ steps.worker-url.outputs.url }}
            **Worker Name:** ${{ steps.random.outputs.name }}-proxy
            **Deployed:** $(date -u)

            This worker proxies to forums.jtechforums.org with automatic domain rewriting.
            The URL will be updated again tomorrow at midnight UTC.
          draft: false
          prerelease: false